Controllers/AltapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proveedoresLECH.Models;

namespace proveedoresLECH.Controllers
{
    public class AltapController : Controller
    {
        // GET: Altap
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Agrega(ProveedoresCLS oProveedoresCLS)
        {
            if (!ModelState.IsValid)
            {
                return View(oProveedoresCLS);
            }
            else
            {
                using (var bd = new proveedoresBDEntities())
                {
                    Proveedores oProveedores = new Proveedores();
                    oProveedores.Codigo = oProveedoresCLS.codigo;
                    oProveedores.Razon_Social = oProveedoresCLS.razonSocial;
                    oProveedores.RFC = oProveedoresCLS.rfc;
                    bd.Proveedores.Add(oProveedores);
                    bd.SaveChanges();
                }
            }
                return RedirectToAction("Index", "Proveedor");
        }
    }
}

Controllers/ModificarpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proveedoresLECH.Models;

namespace proveedoresLECH.Controllers
{
    public class ModificarpController : Controller
    {
        // GET: Modificarp
        public ActionResult Index(int id)
        {
            ProveedoresCLS oProveedorCLS = new ProveedoresCLS();
            using (var bd = new proveedoresBDEntities())
            {
                Proveedores oProveedor = bd.Proveedores.Where(p => p.Id_Proveedor.Equals(id)).First();
                oProveedorCLS.iidProveedor = oProveedor.Id_Proveedor;
                oProveedorCLS.codigo = oProveedor.Codigo;
                oProveedorCLS.razonSocial = oProveedor.Razon_Social;
                oProveedorCLS.rfc = oProveedor.RFC;

            }
            return View(oProveedorCLS);
        }
        [HttpPost]
        public ActionResult Index(ProveedoresCLS oProveedorCLS)
        {
            if (!ModelState.IsValid)
            {
                return View(oProveedorCLS);
            }
            else
            {
                long idProv = oProveedorCLS.iidProveedor;
                using (var bd = new proveedoresBDEntities())
                {
                    Proveedores oProveedor = bd.Proveedores.Where(p => p.Id_Proveedor.Equals(idProv)).First();
                    oProveedor.Codigo = oProveedorCLS.codigo;
                    oProveedor.Razon_Social = oProveedorCLS.razonSocial;
                    oProveedor.RFC = oProveedorCLS.rfc;
                    bd.SaveChanges().ToString();
                }
            }
            return RedirectToAction("Index", "Proveedor");
        }
    }
}

Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proveedoresLECH.Models;

namespace proveedoresLECH.Controllers
{
    public class ProveedorController : Controller
    {
        // GET: Proveedor
        public ActionResult Index()
        {
            List<ProveedoresCLS> listaProovedor = null;
            using (var bd = new proveedoresBDEntities())
            {
                listaProovedor = (from captura in bd.Proveedores
                                  select new ProveedoresCLS
                                  {
                                      iidProveedor = captura.Id_Proveedor,
                                      codigo = captura.Codigo,
                                      razonSocial = captura.Razon_Social,
                                      rfc = captura.RFC
                                  }
                                ).ToList();
            }
            return View(listaProovedor);
            
        }
    }
}

Views/Proveedor/Index.cshtml
@using proveedoresLECH.Models
@model List<ProveedoresCLS>
@{
    ViewBag.Title = "Inicio Proveedor";
    List<SelectListItem> listaEstatus = (List<SelectListItem>)ViewBag.listEstatus;
}
<style>
    .contenedor {
        display: flex;
        align-items: center;
    }
</style>
<div class="row justify-content-md-center" style="margin-bottom:1rem;">
    <div class="col-md-auto justify-content-start" style="margin-bottom:1rem;">
        <div class="card" style="width: 18rem;">
            <div class="card-body contenedor">
                <a href="@Url.Action("Index","Altap")" class="btn stretched-link"><h5 class="card-title">Alta de Proveedor</h5></a>
                <i class="fas fa-user-plus fa-5x"></i>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <table id="tablaProveedor" class="table hover display" style="width:100%">
        <thead>
            <tr>
                <td>@Html.LabelFor(p => Model[0].iidProveedor)</td>
                <td>@Html.LabelFor(p => Model[0].codigo)</td>
                <td>@Html.LabelFor(p => Model[0].razonSocial)</td>
                <td>@Html.LabelFor(p => Model[0].rfc)</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidProveedor</td>
                    <td>@item.codigo</td>
                    <td>@item.razonSocial</td>
                    <td>@item.rfc</td>
                    <td>
                        @Html.ActionLink(" ", "Index", "Modificarp", new { id = item.iidProveedor }, new { @class = "btn btn-outline-primary fas fa-user-edit" })
                        @Html.ActionLink(" ", "Eliminar", "Provedor", new { id = item.iidProveedor }, new { @class = "btn btn-outline-danger fas fa-window-close" })
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#tablaProveedor').DataTable({
            "language":
            {
                url: "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            },
            "paging": false,
        });
        //new $.fn.dataTable.FixedColumns(table);
    });
</script>